language: python
matrix:
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5           
before_install:
- source ./setup_python.sh $MAC_PYTHON_VERSION 'osx'
# install dependencies
install:
  - python --version
  - pip install .
# Set path
before_script: cd ${TRAVIS_BUILD_DIR}/pyIMD/examples
# run tests
script:
  - |
    if ["$TRAVIS_OS_NAME" = "windows"]; then
      python3 -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests
    else 
      python -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests
    fi 
# compile
install:
  - if [ "$TRAVIS_OS_NAME" == "linux"   ] ; then bash $TRAVIS_BUILD_DIR/pyIMD/build/build.sh ; fi

deploy:
  # see https://docs.travis-ci.com/user/deployment/releases/
  - provider: releases
    api_key:
      secure: e0MXN21luRhrvstfQ144EHjZXXemZq8+g1/38vKSnlI/jCkIQ0lC7fopeWw9MlCap+BXFA+/FdeNh/uuTohHK3t8Mrx2UC/elJ21DvyzRlApBOHk7uTou/NBFed0xZqNQmZkcdDtlVeeNCEcw74vEVoMucgWEuX/wm+/KB8fIB36JaYP9BXmdbyQylSPnXZxFG2Mlts8mFFXFRO9EEMi3TYWERtFgq89NEDVSAiw5g0AT11wS05sarzPshrRxNBoFcM6N4SWsoGkMEZylNDB9P+DuXTukFpxoUjAmLWEICD5ZPZnz1KVpzLx89mZaWv9tCHyWQShK5CUk5VwZ+bG1Ky2FkCMeyAWSxny20XxafIe4HZDiTiES7B06lljIllu3PXS0+jJGNraSaVlrNZI7LKjgJqOx3NLk9VgPA72VXLgkoS0YUqQNMTRwkphczul0+iupX0GOmo1Z8Jk5th//nttA0XqTbjVYK+aEpRCURcgqQ9vC2XL5shFmFYHMTfF8iz3Rw3l2PG2mx1RYmxZgT+27laxA0xUXI3PrLQqOXDrENQ7C4yyYGMnXNFB3TYmugoTux68ZMBAdEkG90Q3SQdjgdEelUzng1PZFE2FNtmbszITsrQitV6T692fsjnJzH+cSd2HaAjYf6ebRvyX/2MWguX4pYovc0ci9Vy7dM8=
    file: /home/travis/build/cunyap/pyIMDT/dist/pyIMD
    skip_cleanup: true
    on:
      draft: true
      repo: cunyap/pyIMDT
      file: /home/travis/build/cunyap/pyIMDT/dist/pyIMD
    
