language: python
matrix:
  include:
    - name: "Python 3.5 on Linux"
      python: 3.5           
before_install:
- source ./setup_python.sh $MAC_PYTHON_VERSION 'osx'
# install dependencies
install:
  - python --version
  - pip install .
# Set path
before_script: cd ${TRAVIS_BUILD_DIR}/pyIMD/examples
# run tests
script:
  - |
    if ["$TRAVIS_OS_NAME" = "windows"]; then
      python3 -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests
    else 
      python -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests
    fi 
# compile
install:
  - if [ "$TRAVIS_OS_NAME" == "linux"   ] ; then bash $TRAVIS_BUILD_DIR/pyIMD/build/build.sh ; fi

deploy:
  # see https://docs.travis-ci.com/user/deployment/releases/
  - provider: releases
    api_key:
      secure: fe154cb044733960f0f540ff596ad038ab2612f9
    file: /home/travis/build/cunyap/pyIMDT/dist/pyIMD
    on:
      draft: true
      repo: cunyap/pyIMDT
