language: python
matrix:
  include:
  - name: Python 3.5 on Linux
    python: 3.5
before_install:
- source ./setup_python.sh $MAC_PYTHON_VERSION 'osx'
install:
- if [ "$TRAVIS_OS_NAME" == "linux"   ] ; then bash $TRAVIS_BUILD_DIR/pyIMD/build/build.sh
  ; fi
before_script: cd ${TRAVIS_BUILD_DIR}/pyIMD/examples
script:
- "if [\"$TRAVIS_OS_NAME\" = \"windows\"]; then\n  python3 -m unittest discover -s
  $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nelse \n  python
  -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nfi
  \n"
deploy:
  provider: releases
  api_key:
    secure: iPKCH9TMllGQFisVPQN6VEsRzJA0cemLWbEk/mVD8vcKd0LznUbwjYblspyI+kuz8TwZZf6/FcGXPmhmH1U7s1qExTYRuPjwWWXlRTj/C711nHl9wjriftnf9om29+uOcIxtKu+diwH+jZOVPOfi71LpIN+8B76ZaP4qVJAOS9azogcpV4oXQl4Wy1q33r9A2Z6TacBky6ZsVZto5KyJLBSJ72wJjrsFlKT7dydec+UXk3LU3B4D/+I+y7omWanonXBQlnxMt+N0V+noWCSjQoCCk4uXbXrGkezmzUdgMstf6f3xsZCaje6KkOcimUETfsiqZ5EXdgSI+/NKNVqL5qfBRptHShHaZ89wog8RfvoXyEViGBtEklQDJNcQZNQHo91cHr6QDcI6JHFhPKpkU1WM03HzmUGdIDsdyFmdV0dxXCK21ctVxLZXTMthqOaOx+7hJUGIXWlqoCXNqTH5wHN35gbKYwqNLhAFOGxaI3j/sBK2LMUPfxlSf7cVE/SDFs1iS0etpJY3fDebQNgCGsuOQ//EZ4pdkHAGO76tZYVmgKj08cRLoqJsHH0mJaSi+T7wCeMp/b8AA4C6FValbJh4Wtbfw/mNme4e9kLq8NbtN5smXcwZT5FkG85xuj1olu7NH5LJLq4U7Yv3s6GPcX0v8EnwFSSnibrrrMSeUEw=
  file: "/home/travis/build/cunyap/pyIMDT/dist/pyIMD"
  skip_cleanup: true
  on:
    draft: true
    repo: cunyap/pyIMDT
