language: python
matrix:
  include:
  - name: "Python 3.5 on Linux"
    python: 3.5      
    env: 
      - PYTHON_VERSION=3.5
      - DEPLOY_FILE="/home/travis/build/cunyap/pyIMDT/dist/pyIMD_x64_unix"
  - name: "Python 3.5 on macOS"
    os: osx
    language: generic       # 'language: python' is an error on Travis CI macOS
    env: 
      - PYTHON_VERSION=3.5
      - DEPLOY_FILE="/Users/travis/build/cunyap/pyIMDT/dist/pyIMD_x64_osx.dmg"
before_install:
- source ./setup_python.sh $PYTHON_VERSION 'osx'
install:
- bash $TRAVIS_BUILD_DIR/pyIMD/build/build.sh $TRAVIS_OS_NAME
before_script: cd ${TRAVIS_BUILD_DIR}/pyIMD/examples
script:
- "if [\"$TRAVIS_OS_NAME\" = \"windows\"]; then\n  python3 -m unittest discover -s
  $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nelse \n  python
  -m unittest discover -s $TRAVIS_BUILD_DIR/pyIMD/tests -t $TRAVIS_BUILD_DIR/pyIMD/tests\nfi
  \n"
deploy:
  provider: releases
  api_key:
    secure: FzGUd9Zpilm+qu4hLerGHfu8+RYhAFdqgF8+AZlmrBjaBUXBA/H+WMMh4mnzP1F3Os2ONRpRNJ3hhTzK6Wb8YbtkvVmkbdnkLomJf+m9wY3tI9tLsMotfS08QgtgS5Y6g9Kk5bDL3jYQIcX8JnAP+zVHGxpXIhidQ8Pshbf55M+Rns3ceg7iyjl0dBVYjobZS5UBkJvQ+q2rwxhY8KZ3qvYkMfAcq6DgLR04Db3gVWizdJfWyuhaLzEq3xgrv4It6KOoezmBxGFow04z9n4U17EBYBTKW7kTq+JNIlCSEQuPejADxbLmfmaDQvC1t2VWd5dFI7NMH82oALDUUivMGr493Qt7ZvmGby+c0Gmqiiux6wHQNaXVZnYtRKnn41TX2JRuLa8H3c517N/YZHMUGfH8Ps6utHmuRpg5C9mAX9J03i911P0FJ3BkCpjiI4VNwi11sQ1kPPxqRQm1wbA7C+9OP+WqMnkZJqhszfZ16TlAqPdtPEbq1ALDtfXTru/56O3atDVPq5Llvhad1MXneCzrB4aqpTjsnEobX4ldyxyNef5gPimuQSBiI0IiUiQHqBjmR4FMyTDEKnrD92F/AfZBisYHNhxlRZQX4EWppxQ+kTATTCkx268WE4GmdfrUVzIVcGtr3IjJEJcBC3yIHyzAW8cae1VGcU5vjJVRBa0=
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    draft: true
    condition: $PYTHON_VERSION = 3.5
    repo: cunyap/pyIMDT
